/**
 * ─────────────────────────────────────────────────────────────────────────────
 * Symbiotix · Local Offline Database
 * Powered by Dexie.js (IndexedDB abstraction)
 *
 * All data lives 100 % on-device — never sent to any server.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import Dexie, { type Table } from 'dexie';

// ── Domain types ─────────────────────────────────────────────────────────────

/** A single care task generated by the local LLM */
export interface CareTask {
  id: string;
  task: string;
  frequency: string;
  completed: boolean;
  lastLogged?: number; // Unix timestamp ms
}

/** Toxicity / interaction warning between two scanned entities */
export interface ToxicityWarning {
  targetSpecies: string;
  severity: 'low' | 'medium' | 'high';
  description: string;
}

/** The structured JSON payload produced by our local AI pipeline */
export interface SpeciesScan {
  id?: number;           // auto-incremented by Dexie
  scannedAt: number;     // Unix timestamp ms
  species: string;
  commonName: string;
  type: 'flora' | 'fauna';
  confidence: number;    // 0–1
  imageDataUrl: string;  // Base64 image that NEVER leaves the browser
  care_tasks: CareTask[];
  fun_facts: string[];
  toxicity_warnings: ToxicityWarning[];
  conservation_status: string;
  native_range: string;
  ecosystem_role: string;
  health_notes: string;
}

/** Log entry: when a care task was completed */
export interface CareLog {
  id?: number;
  scanId: number;
  taskId: string;
  taskName: string;
  loggedAt: number;
}

/** Aggregated ecosystem metrics (updated each scan) */
export interface EcosystemStats {
  id?: number;
  totalScans: number;
  floraCount: number;
  faunaCount: number;
  biodiversityIndex: number;
  lastUpdated: number;
}

// ── Database class ────────────────────────────────────────────────────────────

class SymbiotixDB extends Dexie {
  /** All species identified by the local AI */
  scans!: Table<SpeciesScan, number>;
  /** Care task activity log */
  careLogs!: Table<CareLog, number>;
  /** Singleton row for aggregated stats */
  ecosystemStats!: Table<EcosystemStats, number>;

  constructor() {
    super('SymbiotixDB');

    /**
     * Version 1 schema.
     * Indexed fields: scannedAt — enables date-range queries.
     * `type` index — quickly filter flora vs. fauna for Eco-Sync.
     */
    this.version(1).stores({
      scans:          '++id, scannedAt, type, species',
      careLogs:       '++id, scanId, loggedAt',
      ecosystemStats: '++id',
    });
  }
}

// Singleton export — import `db` anywhere in the app
export const db = new SymbiotixDB();

// ── Helper functions ─────────────────────────────────────────────────────────

/**
 * Persist a new scan result and update the aggregate stats row.
 */
export async function saveScan(scan: Omit<SpeciesScan, 'id'>): Promise<number> {
  const id = await db.scans.add(scan as SpeciesScan);

  // Upsert ecosystem stats
  const existing = await db.ecosystemStats.limit(1).first();
  const allScans = await db.scans.count();
  const floraCount = await db.scans.where('type').equals('flora').count();
  const faunaCount = await db.scans.where('type').equals('fauna').count();

  const stats: EcosystemStats = {
    totalScans: allScans,
    floraCount,
    faunaCount,
    // A simplistic biodiversity index — more species types = higher index
    biodiversityIndex: Math.round((floraCount * 0.6 + faunaCount * 0.4) * 10) / 10,
    lastUpdated: Date.now(),
  };

  if (existing?.id) {
    await db.ecosystemStats.update(existing.id, stats);
  } else {
    await db.ecosystemStats.add(stats);
  }

  return id as number;
}

/**
 * Retrieve all past scans ordered newest-first.
 */
export async function getAllScans(): Promise<SpeciesScan[]> {
  return db.scans.orderBy('scannedAt').reverse().toArray();
}

/**
 * Eco-Sync: Given a new scan, find all previously scanned entities
 * whose toxicity_warnings reference the new species (or vice-versa).
 */
export async function findEcoSyncWarnings(
  newScan: Omit<SpeciesScan, 'id'>
): Promise<{ scan: SpeciesScan; warning: ToxicityWarning }[]> {
  const allPrior = await getAllScans();
  const results: { scan: SpeciesScan; warning: ToxicityWarning }[] = [];

  for (const prior of allPrior) {
    // Check if the new species' warnings target any prior species
    for (const warn of newScan.toxicity_warnings) {
      if (prior.species.toLowerCase().includes(warn.targetSpecies.toLowerCase()) ||
          prior.commonName.toLowerCase().includes(warn.targetSpecies.toLowerCase())) {
        results.push({ scan: prior, warning: warn });
      }
    }
    // Also check if a prior scan warned about the THIS species
    for (const warn of prior.toxicity_warnings) {
      if (newScan.species.toLowerCase().includes(warn.targetSpecies.toLowerCase()) ||
          newScan.commonName.toLowerCase().includes(warn.targetSpecies.toLowerCase())) {
        results.push({ scan: prior, warning: warn });
      }
    }
  }

  return results;
}

/**
 * Log a care task completion.
 */
export async function logCareTask(
  scanId: number,
  taskId: string,
  taskName: string
): Promise<void> {
  await db.careLogs.add({ scanId, taskId, taskName, loggedAt: Date.now() });
}

/**
 * Update a care task's `completed` flag in a scan.
 */
export async function toggleCareTask(
  scanId: number,
  taskId: string,
  completed: boolean
): Promise<void> {
  const scan = await db.scans.get(scanId);
  if (!scan) return;

  scan.care_tasks = scan.care_tasks.map((t) =>
    t.id === taskId ? { ...t, completed, lastLogged: completed ? Date.now() : t.lastLogged } : t
  );
  await db.scans.put(scan);
}

/**
 * Fetch the single ecosystem stats row.
 */
export async function getEcosystemStats(): Promise<EcosystemStats | undefined> {
  return db.ecosystemStats.limit(1).first();
}

/**
 * Delete a scan and its associated care logs.
 */
export async function deleteScan(scanId: number): Promise<void> {
  await db.scans.delete(scanId);
  await db.careLogs.where('scanId').equals(scanId).delete();
}
